services:
  - type: web
    name: parkinsons-prediction-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5001
    autoDeploy: true

  - type: web
    name: alzheimers-prediction-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile.alzheimer
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true
